### PR TITLE
Initial transfer of introductory material

### PR DESCRIPTION
**Pull request by tdcox**
Signed-off-by: Terry Cox <terry@bootstrap.je>

### CODE REVIEW

**Comment by tdcox** [comment]
Some notes:

I have tweaked the sequence of the 'Learn' section to represent the sequence of information flow that a reader might benefit from most.

@nyap I have put an example of a call-out here: https://deploy-preview-2--preview-site-cdf-bp.netlify.app/learn/overview/risks/ This is an ugly hack but is an illustration of the need to highlight important points in a visually attractive way, leveraging inbuilt standard mechanisms. Ideally, this would be a stylishly bordered box with a somewhat enlarged font that follows brand colour standards and aligns within the boundaries of the text. A speech bubble would be a nice approach.

I have also put author: tags in the headers to help highlight who is maintaining particular pages.

**Comment by tdcox** [comment]
I have added completely new content in the Learn/Team Culture section.

I think this is probably a good point to review and start to think about early style decisions.

**Comment by nyap** [comment]
> I have put an example of a call-out here: https://deploy-preview-2--preview-site-cdf-bp.netlify.app/learn/overview/risks/

Thanks @tdcox - It looks like the CSS for alerts is defined here:

https://github.com/cdfoundation/best-practices-site/blob/main/themes/docsy/assets/scss/_alerts.scss

And it looks like the recommended approach in the [Docsy docs](https://www.docsy.dev/docs/adding-content/lookandfeel/#project-style-files) is to put style overrides in `assets/scss/_styles_project.scss`. As Tara suggested in our last meeting, we can tackle these changes to alerts in a separate style pass.

**Comment by tdcox** [comment]
Ok, I have tweaked to show how to override the default styling for markdown so that blockquotes now appear as speech bubble callouts with configurable colors. In future, we may want to look at ways of varying this by the type of page.

**Pull request merged**
