### PR TITLE
Tidy up some wording.

### PR DESCRIPTION
**Pull request by justinabrahms**
Minor wording choice from the work done in https://github.com/cdfoundation/best-practices-site/pull/17

### CODE REVIEW

**Comment by tdcox** [comment]
Open to discussion here. The original is more strictly accurate because we are trying to teach that the software pipeline is not intrinsically trustworthy, so deployment governance should be a combination of the attestation of software readiness from the build pipeline combined with additional forms of verification to cross-check that assets have not just been built, but also are the assets that we expect and remain untampered with across any intervening period between a build run and a deployment.

**Comment by justinabrahms** [comment]
I'm game with that idea, just the wording doesn't parse for me.

> Continuous deployment takes that even further to say those artifacts can be *automatically* deployed because of the attestation the software pipeline ensures about correctness.

becomes

> Continuous deployment takes that even further to say those artifacts can be *automatically* deployed because humans have vetted the output and it does the same thing every time.

Something like that?

**Comment by tdcox** [comment]
The original is grammatically correct, although you might substitute ‘asserts’ for ‘ensures’.

The problem with oversimplifying the concept to simplify the language is that you can end up communicating the wrong message as a result. It’s not compulsory to have a human vet the process, as you may actually have independent automated cross-checks that have been designed so as to be provably isolated from any single point of attack.

It might be better to expand this to a paragraph or two of more specific explanation using a more limited vocabulary.

**Comment by justinabrahms** [comment]
I also think there are some supply chain things creeping in here which aren't, in my mind, inherently tied to continuous deployment or delivery.

**Pull request closed without merging**
